### ISSUE TITLE
Auto update form and code

### ISSUE THREAD

**Issue by joepetrillo** [mickasmt/ui-colorgen#2]
Very nice tool! One thing I noticed that would make this even more helpful is if the form values and code examples auto updated after choosing a color. It would be an interesting problem to solve and I may look into the code myself.

**Comment by mickasmt** [comment]
Hey thank you! 
I think the feature you're talking about is the second point on the [roadmap](https://github.com/mickasmt/ui-colorgen#roadmap).
I based myself on the five colors of the shadcn repo but I think I can extend it to all colors as you say.
I'll be back to let you know soon.

**Comment by mickasmt** [comment]
@joepetrillo Hey, I pushed a new feature online. I believe you were talking about this one.
